from typing import Protocol

from pathlib import Path
from .types import (ImageAttachmentLimits, ImageAttachmentRef, ImageRequestPolicy,
                    SaveImageAttachment, StoredImageAttachment, RequestImageAttachment, FileAttachmentRef)


class AttachmentStore(Protocol):
    root: Path
    cache_root: Path
    limits: ImageAttachmentLimits
    def occupied_bytes(self) -> int: ...
    def validate_image(self, data: bytes, media_type: str) -> None: ...
    def save_images_sync(self, inputs: list[SaveImageAttachment]) -> list[ImageAttachmentRef]: ...
    def read_image_sync(self, ref: ImageAttachmentRef) -> StoredImageAttachment: ...
    def read_request_image_sync(self, ref: ImageAttachmentRef, policy: ImageRequestPolicy) -> RequestImageAttachment: ...
    def ref_by_id(self, attachment_id: str) -> ImageAttachmentRef: ...
    def prepare_path(self, path: str | Path) -> SaveImageAttachment: ...
    def save_path(self, path: str | Path) -> ImageAttachmentRef: ...
    def save_file_sync(self, name: str, data: bytes) -> FileAttachmentRef: ...
    async def save_images(self, inputs: list[SaveImageAttachment]) -> list[ImageAttachmentRef]: ...
    async def save_file(self, name: str, data: bytes): ...
    async def read_image(self, ref: ImageAttachmentRef): ...
    async def read_request_image(self, ref: ImageAttachmentRef, policy: ImageRequestPolicy): ...
    def image_host_path(self, ref: ImageAttachmentRef) -> str: ...
    def file_host_path(self, ref) -> str: ...
